name: reminder_app
description: A simple Flutter reminder application.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0" # Update SDK constraints to match API requirements

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^12.0.3
  timezone: ^0.9.1 # Add timezone package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sound/notification-5-158190.mp3 # Add your custom notification sound here if needed
    - assets/images/download.jpeg # Add images if required
